import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { StoreProvider } from "./utils/StoreProvider";
import Navbar from "./reusableComponents/pageConstantElements/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <main>
            <Navbar />
          </main>
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
