import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./utils/StoreProvider";

const inter = Karla({
  weight:["200","300","400","500","600","700","800",],
  subsets: ["latin"],
  variable:"--font-karla"
});

export const metadata: Metadata = {
  title: "Restaurant App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <main>
           
          </main>
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
